"""Generates the per-directory `LATEST.yaml` marker (proposals/schema-registry
§3's filename convention already carries the version — this does not add a
second source of truth, it renders a disposable, regenerated VIEW of what
the directory listing already says, so a human or an agent can see "what is
current, do not edit anything else" without doing that listing/parsing by
hand).

Born from a real incident (see #42/#49/#51): an in-place edit landed on an
already-published `-src<year>.yaml` file instead of a new version file. The
filename convention was never actually violated by design — it was violated
by not looking at it. This module, plus `generate_latest.py`'s drift check
and frozen-file check, makes that mistake mechanically catchable instead of
relying on remembering to look.
"""

from __future__ import annotations

from pathlib import Path

from .paths import SchemaVersion, list_versions

HEADER = (
    "---\n"
    "# Auto-generated by tools/generate_latest.py — DO NOT EDIT BY HAND.\n"
    "# Regenerate with: python -m tools.generate_latest\n"
    "#\n"
    "# current_file is the ONLY file in this directory that may still change\n"
    "# (metadata, a fresh -src<year> re-sign). Every other file here is a\n"
    "# closed, signed content version — never edit it in place. To change\n"
    "# content, add a new <name>.vMAJOR.MINOR.PATCH-src<year>.yaml file\n"
    "# instead (proposals/schema-registry §3/§4), the same way #19 and #51\n"
    "# did it.\n"
)


def _by_content_version(
    versions: list[SchemaVersion],
) -> list[SchemaVersion]:
    """One entry per distinct (major, minor, patch), the freshest -src year
    for each — mirrors registry_validate.check_schema_evolution's own
    "last (freshest) wins" grouping, so LATEST.yaml and the evolution check
    never disagree about what a "version" is."""
    by_content: dict[tuple[int, int, int], SchemaVersion] = {}
    for v in versions:
        by_content[v.content_version] = v
    return [by_content[k] for k in sorted(by_content)]


def render_latest(schema_dir: Path) -> str | None:
    """The LATEST.yaml text for one schema directory, or None if the
    directory has no parseable schema-version files (nothing to mark)."""
    versions = list_versions(schema_dir)
    if not versions:
        return None
    content_versions = _by_content_version(versions)
    current = content_versions[-1]

    lines = [HEADER.rstrip("\n")]
    lines.append(f"schema: {current.name}")
    lines.append("current:")
    lines.append(f"  version: {current.content_version_str}")
    lines.append(f"  file: {current.path.name}")
    lines.append("all_versions:")
    for v in content_versions:
        lines.append(f"  - version: {v.content_version_str}")
        lines.append(f"    file: {v.path.name}")
    lines.append("")
    return "\n".join(lines)
